<?php
 return [
    [
        'title' => 'Appartamento elegante in zona residenziale',
        'description' => 'Splendido appartamento completamente arredato in una zona tranquilla e ben collegata.',
        'address' => 'Via dei Cipressi 5, 00123 Milano MI',
        'bed' => 3,
        'bathroom' => 2,
        'sq_m' => 110,
        'latitude' => 45.4789,
        'longitude' => 9.2285,
        'image' => 'img/appartamento1.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento moderno con terrazza panoramica',
        'description' => 'Appartamento di design con una spaziosa terrazza da cui si gode una vista mozzafiato sulla città.',
        'address' => 'Via della Libertà 20, 00100 Roma RM',
        'bed' => 2,
        'bathroom' => 1,
        'sq_m' => 90,
        'latitude' => 41.9028,
        'longitude' => 12.4964,
        'image' => 'img/appartamento2.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento accogliente vicino al centro storico',
        'description' => 'Accogliente appartamento situato a pochi passi dal centro storico, ideale per una coppia o una piccola famiglia.',
        'address' => 'Via Garibaldi 15, 20121 Milano MI',
        'bed' => 1,
        'bathroom' => 1,
        'sq_m' => 60,
        'latitude' => 45.4641,
        'longitude' => 9.1900,
        'image' => 'img/appartamento3.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento luminoso con giardino privato',
        'description' => 'Appartamento luminoso e spazioso con un bellissimo giardino privato, perfetto per chi ama la tranquillità.',
        'address' => 'Via dei Fiori 10, 50123 Firenze FI',
        'bed' => 4,
        'bathroom' => 2,
        'sq_m' => 130,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'image' => 'img/appartamento4.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento di lusso nel cuore della città',
        'description' => 'Elegante appartamento di lusso situato nel centro storico della città, con servizi di alta qualità e finiture di pregio.',
        'address' => 'Piazza San Marco 1, 30124 Venezia VE',
        'bed' => 2,
        'bathroom' => 2,
        'sq_m' => 100,
        'latitude' => 45.4342,
        'longitude' => 12.3387,
        'image' => 'img/appartamento5.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento con vista sul parco',
        'description' => 'Appartamento con affaccio sul verde di un tranquillo parco cittadino, ideale per chi ama la natura e la tranquillità.',
        'address' => 'Via dei Pini 30, 40123 Bologna BO',
        'bed' => 3,
        'bathroom' => 2,
        'sq_m' => 95,
        'latitude' => 44.4949,
        'longitude' => 11.3426,
        'image' => 'img/appartamento6.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento ristrutturato con stile',
        'description' => 'Appartamento completamente ristrutturato con stile e attenzione ai dettagli, situato in una zona ben servita e tranquilla.',
        'address' => 'Via delle Rose 8, 20100 Milano MI',
        'bed' => 2,
        'bathroom' => 1,
        'sq_m' => 75,
        'latitude' => 45.4789,
        'longitude' => 9.2285,
        'image' => 'img/appartamento7.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento con terrazza e vista sul fiume',
        'description' => 'Appartamento con una grande terrazza da cui si gode una magnifica vista sul fiume, ideale per serate estive.',
        'address' => 'Lungarno 2, 50100 Firenze FI',
        'bed' => 3,
        'bathroom' => 2,
        'sq_m' => 110,
        'latitude' => 43.7696,
        'longitude' => 11.2558,
        'image' => 'img/appartamento8.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento spazioso con cucina moderna',
        'description' => 'Ampio appartamento con una cucina moderna e ben attrezzata, ideale per chi ama cucinare e ricevere ospiti.',
        'address' => 'Via Roma 5, 00100 Roma RM',
        'bed' => 4,
        'bathroom' => 3,
        'sq_m' => 150,
        'latitude' => 41.9028,
        'longitude' => 12.4964,
        'image' => 'img/appartamento9.jpg',
        'is_visible' => true,
    ],
    [
        'title' => 'Appartamento con vista panoramica sulla città',
        'description' => 'Appartamento situato in una posizione privilegiata con una vista panoramica sulla città, luminoso e ben ventilato.',
        'address' => 'Piazza del Popolo 10, 00187 Roma RM',
        'bed' => 2,
        'bathroom' => 2,
        'sq_m' => 85,
        'latitude' => 41.9139,
        'longitude' => 12.4763,
        'image' => 'img/appartamento10.jpg',
        'is_visible' => true,
    ],
];